# coding: utf-8

"""
    Apache CouchDB API

    OpenAPI description of the Apache CouchDB 3.x HTTP API. This is the single source of truth for all generated CouchDB SDKs. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from couchdb_client.models.changes_result import ChangesResult

from couchdb_client.api_client import ApiClient, RequestSerialized
from couchdb_client.api_response import ApiResponse
from couchdb_client.rest import RESTResponseType


class ChangesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_changes(
        self,
        db: Annotated[str, Field(strict=True, description="Database name")],
        feed: Optional[StrictStr] = None,
        since: Optional[StrictStr] = None,
        include_docs: Optional[StrictBool] = None,
        limit: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        timeout: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Longpoll timeout in milliseconds")] = None,
        descending: Optional[StrictBool] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ChangesResult:
        """Database changes feed (normal or longpoll)


        :param db: Database name (required)
        :type db: str
        :param feed:
        :type feed: str
        :param since:
        :type since: str
        :param include_docs:
        :type include_docs: bool
        :param limit:
        :type limit: int
        :param timeout: Longpoll timeout in milliseconds
        :type timeout: int
        :param descending:
        :type descending: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_changes_serialize(
            db=db,
            feed=feed,
            since=since,
            include_docs=include_docs,
            limit=limit,
            timeout=timeout,
            descending=descending,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ChangesResult",
            '404': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_changes_with_http_info(
        self,
        db: Annotated[str, Field(strict=True, description="Database name")],
        feed: Optional[StrictStr] = None,
        since: Optional[StrictStr] = None,
        include_docs: Optional[StrictBool] = None,
        limit: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        timeout: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Longpoll timeout in milliseconds")] = None,
        descending: Optional[StrictBool] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ChangesResult]:
        """Database changes feed (normal or longpoll)


        :param db: Database name (required)
        :type db: str
        :param feed:
        :type feed: str
        :param since:
        :type since: str
        :param include_docs:
        :type include_docs: bool
        :param limit:
        :type limit: int
        :param timeout: Longpoll timeout in milliseconds
        :type timeout: int
        :param descending:
        :type descending: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_changes_serialize(
            db=db,
            feed=feed,
            since=since,
            include_docs=include_docs,
            limit=limit,
            timeout=timeout,
            descending=descending,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ChangesResult",
            '404': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_changes_without_preload_content(
        self,
        db: Annotated[str, Field(strict=True, description="Database name")],
        feed: Optional[StrictStr] = None,
        since: Optional[StrictStr] = None,
        include_docs: Optional[StrictBool] = None,
        limit: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        timeout: Annotated[Optional[Annotated[int, Field(strict=True, ge=0)]], Field(description="Longpoll timeout in milliseconds")] = None,
        descending: Optional[StrictBool] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Database changes feed (normal or longpoll)


        :param db: Database name (required)
        :type db: str
        :param feed:
        :type feed: str
        :param since:
        :type since: str
        :param include_docs:
        :type include_docs: bool
        :param limit:
        :type limit: int
        :param timeout: Longpoll timeout in milliseconds
        :type timeout: int
        :param descending:
        :type descending: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_changes_serialize(
            db=db,
            feed=feed,
            since=since,
            include_docs=include_docs,
            limit=limit,
            timeout=timeout,
            descending=descending,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ChangesResult",
            '404': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_changes_serialize(
        self,
        db,
        feed,
        since,
        include_docs,
        limit,
        timeout,
        descending,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if db is not None:
            _path_params['db'] = db
        # process the query parameters
        if feed is not None:
            
            _query_params.append(('feed', feed))
            
        if since is not None:
            
            _query_params.append(('since', since))
            
        if include_docs is not None:
            
            _query_params.append(('include_docs', include_docs))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if timeout is not None:
            
            _query_params.append(('timeout', timeout))
            
        if descending is not None:
            
            _query_params.append(('descending', descending))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'basicAuth', 
            'cookieAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/{db}/_changes',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


