# coding: utf-8

# flake8: noqa

"""
    Apache CouchDB API

    OpenAPI description of the Apache CouchDB 3.x HTTP API. This is the single source of truth for all generated CouchDB SDKs. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# import apis into sdk package
from couchdb_client.api.authentication_api import AuthenticationApi
from couchdb_client.api.databases_api import DatabasesApi
from couchdb_client.api.design_documents_api import DesignDocumentsApi
from couchdb_client.api.documents_api import DocumentsApi
from couchdb_client.api.query_api import QueryApi
from couchdb_client.api.server_api import ServerApi

# import ApiClient
from couchdb_client.api_response import ApiResponse
from couchdb_client.api_client import ApiClient
from couchdb_client.configuration import Configuration
from couchdb_client.exceptions import OpenApiException
from couchdb_client.exceptions import ApiTypeError
from couchdb_client.exceptions import ApiValueError
from couchdb_client.exceptions import ApiKeyError
from couchdb_client.exceptions import ApiAttributeError
from couchdb_client.exceptions import ApiException

# import models into sdk package
from couchdb_client.models.all_docs_query import AllDocsQuery
from couchdb_client.models.all_docs_result import AllDocsResult
from couchdb_client.models.all_docs_result_rows_inner import AllDocsResultRowsInner
from couchdb_client.models.all_docs_result_rows_inner_value import AllDocsResultRowsInnerValue
from couchdb_client.models.bulk_docs import BulkDocs
from couchdb_client.models.database_information import DatabaseInformation
from couchdb_client.models.database_information_props import DatabaseInformationProps
from couchdb_client.models.database_information_sizes import DatabaseInformationSizes
from couchdb_client.models.document import Document
from couchdb_client.models.document_result import DocumentResult
from couchdb_client.models.error import Error
from couchdb_client.models.find_query import FindQuery
from couchdb_client.models.find_result import FindResult
from couchdb_client.models.index_definition_request import IndexDefinitionRequest
from couchdb_client.models.index_definition_request_index import IndexDefinitionRequestIndex
from couchdb_client.models.index_result import IndexResult
from couchdb_client.models.indexes_information import IndexesInformation
from couchdb_client.models.indexes_information_indexes_inner import IndexesInformationIndexesInner
from couchdb_client.models.ok import Ok
from couchdb_client.models.server_information import ServerInformation
from couchdb_client.models.server_information_vendor import ServerInformationVendor
from couchdb_client.models.session_created import SessionCreated
from couchdb_client.models.session_information import SessionInformation
from couchdb_client.models.session_information_info import SessionInformationInfo
from couchdb_client.models.session_information_user_ctx import SessionInformationUserCtx
from couchdb_client.models.session_request import SessionRequest
from couchdb_client.models.up_information import UpInformation
from couchdb_client.models.uuids_result import UuidsResult
from couchdb_client.models.view_query import ViewQuery
from couchdb_client.models.view_result import ViewResult
from couchdb_client.models.view_result_rows_inner import ViewResultRowsInner
