# coding: utf-8

"""
    Apache CouchDB API

    OpenAPI description of the Apache CouchDB 3.x HTTP API. This is the single source of truth for all generated CouchDB SDKs. 

    The version of the OpenAPI document: 0.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class AllDocsQuery(BaseModel):
    """
    AllDocsQuery
    """ # noqa: E501
    include_docs: Optional[StrictBool] = False
    keys: Optional[List[StrictStr]] = None
    start_key: Optional[StrictStr] = None
    end_key: Optional[StrictStr] = None
    limit: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    skip: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    descending: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["include_docs", "keys", "start_key", "end_key", "limit", "skip", "descending"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AllDocsQuery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AllDocsQuery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "include_docs": obj.get("include_docs") if obj.get("include_docs") is not None else False,
            "keys": obj.get("keys"),
            "start_key": obj.get("start_key"),
            "end_key": obj.get("end_key"),
            "limit": obj.get("limit"),
            "skip": obj.get("skip"),
            "descending": obj.get("descending")
        })
        return _obj


