# coding: utf-8

"""
    Apache CouchDB API

    OpenAPI description of the Apache CouchDB 3.x HTTP API. This is the single source of truth for all generated CouchDB SDKs. 

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from couchdb_client.models.attachment import Attachment
from couchdb_client.models.revisions import Revisions
from typing import Optional, Set
from typing_extensions import Self

class Document(BaseModel):
    """
    A JSON document. Arbitrary user fields are allowed.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="_id")
    rev: Optional[StrictStr] = Field(default=None, alias="_rev")
    deleted: Optional[StrictBool] = Field(default=None, alias="_deleted")
    attachments: Optional[Dict[str, Attachment]] = Field(default=None, alias="_attachments")
    conflicts: Optional[List[StrictStr]] = Field(default=None, alias="_conflicts")
    revisions: Optional[Revisions] = Field(default=None, alias="_revisions")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["_id", "_rev", "_deleted", "_attachments", "_conflicts", "_revisions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Document from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in attachments (dict)
        _field_dict = {}
        if self.attachments:
            for _key_attachments in self.attachments:
                if self.attachments[_key_attachments]:
                    _field_dict[_key_attachments] = self.attachments[_key_attachments].to_dict()
            _dict['_attachments'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of revisions
        if self.revisions:
            _dict['_revisions'] = self.revisions.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Document from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # couchdb-sdk-generator override: only pass keys present in `obj`, so
        # absent fields stay unset. Otherwise untyped fields (view start_key)
        # count as explicitly null and to_dict() sends them as null.
        _obj = cls.model_validate({_k: _v for _k, _v in {
            "_id": obj.get("_id"),
            "_rev": obj.get("_rev"),
            "_deleted": obj.get("_deleted"),
            "_attachments": dict(
                (_k, Attachment.from_dict(_v))
                for _k, _v in obj["_attachments"].items()
            )
            if obj.get("_attachments") is not None
            else None,
            "_conflicts": obj.get("_conflicts"),
            "_revisions": Revisions.from_dict(obj["_revisions"]) if obj.get("_revisions") is not None else None
        }.items() if _k in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


