# coding: utf-8

"""
    Apache CouchDB API

    OpenAPI description of the Apache CouchDB 3.x HTTP API. This is the single source of truth for all generated CouchDB SDKs. 

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from couchdb_client.models.index_definition_request_index import IndexDefinitionRequestIndex
from typing import Optional, Set
from typing_extensions import Self

class IndexDefinitionRequest(BaseModel):
    """
    IndexDefinitionRequest
    """ # noqa: E501
    index: IndexDefinitionRequestIndex
    ddoc: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    type: Optional[StrictStr] = 'json'
    partitioned: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["index", "ddoc", "name", "type", "partitioned"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['json', 'text']):
            raise ValueError("must be one of enum values ('json', 'text')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IndexDefinitionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of index
        if self.index:
            _dict['index'] = self.index.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IndexDefinitionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # couchdb-sdk-generator override: only pass keys present in `obj`, so
        # absent fields stay unset. Otherwise untyped fields (view start_key)
        # count as explicitly null and to_dict() sends them as null.
        _obj = cls.model_validate({_k: _v for _k, _v in {
            "index": IndexDefinitionRequestIndex.from_dict(obj["index"]) if obj.get("index") is not None else None,
            "ddoc": obj.get("ddoc"),
            "name": obj.get("name"),
            "type": obj.get("type") if obj.get("type") is not None else 'json',
            "partitioned": obj.get("partitioned")
        }.items() if _k in obj})
        return _obj


