# coding: utf-8

"""
    Apache CouchDB API

    OpenAPI description of the Apache CouchDB 3.x HTTP API. This is the single source of truth for all generated CouchDB SDKs. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from couchdb_client.models.replication_request_source import ReplicationRequestSource
from couchdb_client.models.replication_request_target import ReplicationRequestTarget
from typing import Optional, Set
from typing_extensions import Self

class ReplicationRequest(BaseModel):
    """
    ReplicationRequest
    """ # noqa: E501
    source: ReplicationRequestSource
    target: ReplicationRequestTarget
    create_target: Optional[StrictBool] = None
    continuous: Optional[StrictBool] = None
    cancel: Optional[StrictBool] = None
    doc_ids: Optional[List[StrictStr]] = None
    selector: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["source", "target", "create_target", "continuous", "cancel", "doc_ids", "selector"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReplicationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of target
        if self.target:
            _dict['target'] = self.target.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReplicationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source": ReplicationRequestSource.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "target": ReplicationRequestTarget.from_dict(obj["target"]) if obj.get("target") is not None else None,
            "create_target": obj.get("create_target"),
            "continuous": obj.get("continuous"),
            "cancel": obj.get("cancel"),
            "doc_ids": obj.get("doc_ids"),
            "selector": obj.get("selector")
        })
        return _obj


