# coding: utf-8

"""
    Apache CouchDB API

    OpenAPI description of the Apache CouchDB 3.x HTTP API. This is the single source of truth for all generated CouchDB SDKs. 

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SchedulerJobsJobsInner(BaseModel):
    """
    SchedulerJobsJobsInner
    """ # noqa: E501
    id: Optional[StrictStr] = None
    database: Optional[StrictStr] = None
    doc_id: Optional[StrictStr] = None
    source: Optional[StrictStr] = None
    target: Optional[StrictStr] = None
    user: Optional[StrictStr] = None
    node: Optional[StrictStr] = None
    pid: Optional[StrictStr] = None
    start_time: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "database", "doc_id", "source", "target", "user", "node", "pid", "start_time"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SchedulerJobsJobsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if database (nullable) is None
        # and model_fields_set contains the field
        if self.database is None and "database" in self.model_fields_set:
            _dict['database'] = None

        # set to None if doc_id (nullable) is None
        # and model_fields_set contains the field
        if self.doc_id is None and "doc_id" in self.model_fields_set:
            _dict['doc_id'] = None

        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SchedulerJobsJobsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # couchdb-sdk-generator override: only pass keys present in `obj`, so
        # absent fields stay unset. Otherwise untyped fields (view start_key)
        # count as explicitly null and to_dict() sends them as null.
        _obj = cls.model_validate({_k: _v for _k, _v in {
            "id": obj.get("id"),
            "database": obj.get("database"),
            "doc_id": obj.get("doc_id"),
            "source": obj.get("source"),
            "target": obj.get("target"),
            "user": obj.get("user"),
            "node": obj.get("node"),
            "pid": obj.get("pid"),
            "start_time": obj.get("start_time")
        }.items() if _k in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


