# coding: utf-8

"""
    Apache CouchDB API

    OpenAPI description of the Apache CouchDB 3.x HTTP API. This is the single source of truth for all generated CouchDB SDKs. 

    The version of the OpenAPI document: 0.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ViewQuery(BaseModel):
    """
    ViewQuery
    """ # noqa: E501
    include_docs: Optional[StrictBool] = False
    reduce: Optional[StrictBool] = None
    group: Optional[StrictBool] = None
    group_level: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    keys: Optional[List[Any]] = None
    start_key: Optional[Any] = None
    end_key: Optional[Any] = None
    limit: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    skip: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    descending: Optional[StrictBool] = None
    update: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["include_docs", "reduce", "group", "group_level", "keys", "start_key", "end_key", "limit", "skip", "descending", "update"]

    @field_validator('update')
    def update_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['true', 'false', 'lazy']):
            raise ValueError("must be one of enum values ('true', 'false', 'lazy')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ViewQuery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if start_key (nullable) is None
        # and model_fields_set contains the field
        if self.start_key is None and "start_key" in self.model_fields_set:
            _dict['start_key'] = None

        # set to None if end_key (nullable) is None
        # and model_fields_set contains the field
        if self.end_key is None and "end_key" in self.model_fields_set:
            _dict['end_key'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ViewQuery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "include_docs": obj.get("include_docs") if obj.get("include_docs") is not None else False,
            "reduce": obj.get("reduce"),
            "group": obj.get("group"),
            "group_level": obj.get("group_level"),
            "keys": obj.get("keys"),
            "start_key": obj.get("start_key"),
            "end_key": obj.get("end_key"),
            "limit": obj.get("limit"),
            "skip": obj.get("skip"),
            "descending": obj.get("descending"),
            "update": obj.get("update")
        })
        return _obj


